# 에러 & 예외 처리

## 1. 에러

> 에러의 종류에 대해 알아보자.



### 1.1 문법 에러

> 문법에러가 있으면 실행이 안된다.



- 에러가 생기면 `SyntaxError`라는 키워드와 함께 상세 내용이 나옴
- `파일이름`과 `줄번호`, `^` 문자를 통해 문제가 발생한 위치를 표현
- `parser`는  에러위치를 작은 '화살표(`^`)'로 표시



### 1.2 예외

> 실행 도중 예상치 못한 상황이 생기면 프로그램 실행을 멈춤

- 문법적으로는 옳지만, 실행시 발생하는 에러



## 2. 예외 처리

### 2.1 `try`&`except`

> `try`문을 이용하여 예외 처리를 할 수 있다.



- 사용법

```python
try:
    <코드 블럭 1>
except (예외):
    <코드 블럭 2>
```

- `try` 아래의 코드 블럭이 먼저 실행
- 예외가 발생하지 않으면 `except` 없이 실행 종료
- 예외가 발생하면 남은 부분을 수행하지 않고 `except`가 실행

```python
try:
  num = input('값을 입력하시오 : ')
  print(int(num))
except:
  print('숫자를 입력하세요')
```

```python
값을 입력하시오 : ㄴㅇㄹ
숫자를 입력하세요
```



### 2.2 에러 메시지 처리 `as`

> `as` 키워드를 활용하여 에러 메시지를 보여줄수 있다.



- 사용법

```python
try:
    <코드 1>
except 예외 as err:
    <코드 2>
```

```python
try:
  empty_list = []
  print(empty_list[-1])
except IndexError as err:
  print(err)
```

```python
list index out of range
```



### 2.3 복수의 예외 처리

> 하나 이상의 예외를 모두 처리할 수 있다.
>
> 괄호가 있는 튜플로 여러 개의 예외를 지정 가능



- 사용법

```python
try:
    <코드 블럭 1>
except (예외1, 예외2):
    <코드 블럭 2>
 
 
try:
    <코드 블럭 1>
except 예외1:
    <코드 블럭 2>
except 예외2:
    <코드 블럭 3>
```



- 예시 1

```python
try:
  num = input('100으로 나눌 값을 입력하시오: ')
  100/int(num)
except ValueError:
  print('숫자를 입력하시오')
except ZeroDivisionError:
  print('0이 아닌 다른걸 입력하시오')
```

```python
100으로 나눌 값을 입력하시오: 0
0이 아닌 다른걸 입력하시오
100으로 나눌 값을 입력하시오: ㄴㄴㄴ
숫자를 입력하시오
```

- 예시 2

```python
try:
  num = input('100으로 나눌 값을 입력하시오: ')
  100/int(num)
except (ValueError, ZeroDivisionError):
  print('뭔가 잘못됨')
```

```python
100으로 나눌 값을 입력하시오: ㅇㅇㅇ
뭔가 잘못됨
```

- 여기서 중요한점 : 에러가 순차적으로 수행됨으로, 가장 작은 범주부터 시작해야 한다.

```python
try:
  num = input('100으로 나눌 값을 입력하시오: ')
  100/int(num)
except Exception:
  print('에러 발생')
except ValueError:
  print('숫자를 입력하시오')
except ZeroDivisionError:
  print('0이 아닌 다른걸 입력하시오')
```

```python
100으로 나눌 값을 입력하시오: ㄴㅇㄹㄴ
에러 발생
100으로 나눌 값을 입력하시오: 0
에러 발생
```



#### 2.3.1 else

- 에러가 발생하지 않는 경우 실행 시킬 문장은 else 활용
- else는 except 코드 뒤에 와야함
- try 코드 블럭에 예외를 일으키지 않을때 실행되어야 하는 코드에 사용



- 활용법

```python
try:
    <코드 블럭 1>
except 예외:
    <코드 블럭 2>
else:
    <코드 블럭 3>
```

- 예시

```python
try:
    numbers = [1, 2, 3]
    number = numbers[2]
except IndexError:
    print('오류 발생')
else:
  print(number)
```

```python
3
```



#### 2.3.2 finally

- 어떤 경우에든 반드시 실행해야하는 코드에는 `finally`를 활용한다.
- 즉, 모든 상황에 실행되어야만 하는 코드를 정의하는데 활용한다.
- 예외의 발생 여부과 관계없이 항상 실행된다.



- 활용법

```python
try:
    <코드 블럭 1>
except 예외:
    <코드 블럭 2>
finally:
    <코드 블럭 3>
```

- 예시

```python
try:
    languages = {'python': 'good'}
    languages['java']
except KeyError as err:
    print(f'{err}는 딕셔너리에 없는 키입니다.')
finally:
  print('감사합니다')
```

```python
'java'는 딕셔너리에 없는 키입니다.
감사합니다
```



### 2.4 예외 발생 시키기

#### 2.4.1 raise

> `raise`를 통해 예외를 강제로 발생시킬 수 있습니다.

- 활용법

```python
raise <에러>('메시지')
```

#### 2.4.2 assert

> 보통 **상태를 검증하는데 사용**되며 무조건 `AssertionError`가 발생합니다.

- 사용법

```python
assert Boolean expression, error message
 
assert type(1) == int, '문자열을 입력하였습니다.'
```



